USE KHOTHUOC
CREATE TABLE TONKHO(
THOIGIAN CHAR(6), 
MAKHO CHAR(8),
MATHUOC CHAR(8),
SLD NUMERIC (10,2),
TTD NUMERIC (11,0),
SLN NUMERIC (10,2),
TTN NUMERIC (11,0),
SLX NUMERIC (10,2),
TTX NUMERIC (11,0),
SLC NUMERIC (10,2),
TTC NUMERIC (11,0),
PRIMARY KEY (THOIGIAN, MAKHO, MATHUOC)
)

SELECT *
FROM TONKHODAUKY